version: 0.0
os: linux
files:
  - source: .
    destination: /opt/MyApp
hooks:
  BeforeInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_script.sh
      timeout: 300
      runas: root
