version: 0.0
os: linux
files:
  - source: CVscript.py
    destination: /opt/MyApp
  - source: empire.jpg
    destination: /opt/MyApp
hooks:
  ApplicationStart:
    - location: scripts/run_script.sh
      timeout: 300
      runas: Administrator
